/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package many.to.many.gradle.app;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
